#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# If the control reaches this step, the service can be enabled and started

set -e

systemctl --user daemon-reload
systemctl --user enable teaspeak.service
systemctl --user restart teaspeak.service

if [ "${WEB_ENABLED:-1}" = "1" ]; then
	systemctl --user enable teaspeak-web.service
	systemctl --user restart teaspeak-web.service
else
	systemctl --user disable --now teaspeak-web.service || true
fi
