#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import json
import agent
import sys

# Consume stdin as required by the action protocol.
json.load(sys.stdin)

# Remove public firewall rules created during configuration.
agent.remove_public_service(os.environ["MODULE_ID"])

agent.tasks.run(
	agent_id=agent.resolve_agent_id("traefik@node"),
	action="delete-route",
	data={"instance": os.environ["MODULE_ID"] + "-web"},
	extra={"isNotificationHidden": True},
)
