FROM nginx:1.30.1-alpine3.23-slim

ARG TEAWEB_VERSION=59737567

COPY default.conf /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/nginx.conf

RUN apk update --no-cache \
    && apk upgrade --no-cache \
    && apk add --no-cache \
        unzip \
    && mkdir -p /var/www/TeaWeb \
    && wget -q -O /var/www/TeaWeb/TeaWeb-release.zip "https://github.com/TeaSpeak/TeaWeb/releases/download/${TEAWEB_VERSION}/TeaWeb-release-${TEAWEB_VERSION}.zip" \
    && unzip -oq /var/www/TeaWeb/TeaWeb-release.zip -d /var/www/TeaWeb \
    && rm /var/www/TeaWeb/TeaWeb-release.zip

ENV TEAWEB_VERSION="${TEAWEB_VERSION}"

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]